### ISSUE TITLE
[proposal] update boost from 1.64 to 1.69 (or other version support C++17)

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/apothecary#122]
oF 0.10.1 on boost 1.64 now.
but, boost 1.64 uses `std::auto_ptr`, and this is deleted on  C++17.
and other libraries are OK to use C++17 maybe...

i try to replace 1.69 with apothecary and it succeed (and perhaps it works correctly) on below env:
* macOS 10.13.6
* Xcode 10.1
* oF 0.10.1 osx release

but i don't/can't test other many envs.

i hope to update.

thanks.

**Comment by tgfrerer** [comment]
If I remember correctly, we're using boost mainly to get early access to std::filesystem, which should be part of the standard library in C++17. 

This means, if your toolchain supports C++17, there shouldn't be a need to use boost with openFrameworks, but you could use <filesystem> directly from the C++ standard library.

**Comment by 2bbb** [comment]
@tgfrerer 
oh, really? boost is only for `<filesystem>`?
i'll try it soon!

thanks!!

**Comment by 2bbb** [comment]
<img width="270" alt="2019-02-25 19 10 30" src="https://user-images.githubusercontent.com/200899/53330151-2052f880-3931-11e9-94c9-ace91bd627da.png">
oh yeah... maybe it's fact!

**Comment by arturoc** [comment]
yes, there's currently a flag that you can add to the define to completely exclude boost: `OF_USING_STD_FS` if you define that in ofConstants.h or just add it to the compiler as a define boost will be completely excluded and OF will use internally std::filesystem from experimental or from plain std if c++17 is enabled.

The plan is to enable that flag once filesystem is supported across the supported compilers for a couple of versions so updating boost probably doesn't make much sense since it's on its way out.
