### ISSUE TITLE
Apple Silicon?

### ISSUE THREAD

**Issue by armadillu** [openframeworks/apothecary#161]
Anyone has one? Wondering how hard will it be to get all the dependencies compiled for it...

**Comment by ofTheo** [comment]
I have one coming soon. 
Hoping the current iOS libs could be reused but not 100% sure.

**Comment by danoli3** [comment]
We will need to write some script updates for arm64 Mac, it can’t just use
iOS slice.
I am currently updating the scripts for iOS

I have an apple silicon device now and also can jump on that this week.

We will need to progress the metal support very soon though, also a plan of
mine to finish in the next two weeks

**Comment by ofTheo** [comment]
Awesome @danoli3 

I am guessing then it might be a lipo solution where instead of doing 32bit / 64bit intel libs we lipo 64bit intel and arm64. 
As long as the current libs compile fine to arm64 then the rest should be easy as none of the linker stuff would have to change. 

I should have my mac mini in a couple of days and can help out on the effort. 

I believe OpenGL does still run on Apple Silicon, I'd be curious to chat more about the Metal stuff though. 
Maybe that could be another thread / issue?

**Comment by ofTheo** [comment]
I just gave GLFW a try on the Apple Silicon Mini I have and it works great.
 
I can start some PRs for updating the formulas ( swapping out i386 for arm64 and keeping x86_64  ) but I think we'll need to update the CI to be at least macos 10.14 and Xcode 12.  

macos 10.14 / Xcode 12 should allow builds to be compatible both with older macos versions and the newer macos 11.0 / Apple Silicon machines.

@arturoc is that something you can help with? Or we could sync up on how to do this and I could take it on. 

Thanks!

**Comment by arturoc** [comment]
I'm too busy at the moment but changing the xcode version should be pretty straightforward just change it in travis.yml

Surely somethings will fail but since we already compile for arm64 for ios i think in general this should be relatively painless
