### ISSUE TITLE
MSYS2 rtaudio built with ASIO option but doesn't compile asio files

### ISSUE THREAD

**Issue by oxillo** [openframeworks/apothecary#73]
Some Of sound examples don't compile as ASIO functions are not built into RtAudio Lib. 
Even if we build with ASIO, I do not get any sound output. 
I would suggest removing ASIO option when building RtAudio lib.

**Comment by arturoc** [comment]
some people have complained about asio not working too but this is the default api if you want to do anything serious with real time audio. it might be that some cards need drivers or something like that. i guess now that the api can be selected we could default to direct sound instead of asio but still give the option to use asio
